### ISSUE TITLE
Hidden registration link on login page

### ISSUE THREAD

**Issue by Feeshay** [hack4impact-uiuc/ymca#136]
Title - you have to zoom out to see it, idk if there's a way to make it so it always shows without having to adjust screen size

![image](https://user-images.githubusercontent.com/36244017/74897373-86b00280-535c-11ea-9ab5-61fe2a0efb41.png)

^^^ where tf?

**Comment by jackieo5023** [comment]
This is *potentially* due to us mixing px/em/percents/vh, but don't quote me on that
