### ISSUE TITLE
Ensure required fields on resource form

### ISSUE THREAD

**Issue by n3a9** [hack4impact-uiuc/ymca#195]
![image](https://user-images.githubusercontent.com/7104017/77807418-0492b800-7045-11ea-8c2f-376035771113.png)

Currently, cost is a required value in the Resource model, but not required in the form for adding a resource. Double check that all of the required values in the resource model are required in the admin form.

**Comment by kenetec** [comment]
On my end, the only fields I see that are required in the model are category, subcategory, name, and description. Should cost be a required value in the model?
